[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/"
  to = "/markets"
  status = 302
  force = true

[functions]
    directory = "functions/"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"

[build]
    publish = ".next"